name: bb
on:
  issues:
    types: [opened, reopened, edited, closed, labeled, unlabeled]
  pull_request:
    types: [opened, reopened, edited, closed, labeled, unlabeled]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
